---
- name: Include package installation tasks
  ansible.builtin.include_tasks: install_packages.yml

- name: Remove console settings from /boot/firmware/cmdline.txt
  ansible.builtin.replace:
    path: /boot/firmware/cmdline.txt
    regexp: 'console=serial0,115200 '
    replace: ''
  notify: Reboot System

- name: Determine Raspberry Pi model and set overlay in /boot/config.txt
  ansible.builtin.shell: "cat /proc/device-tree/model"
  register: pi_model
  changed_when: false

- name: Add appropriate dtoverlay configuration to /boot/firmware/config.txt for Raspberry Pi 3
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    insertafter: EOF
    line: 'dtoverlay=pi3-disable-bt'
    create: true
  when: "'Raspberry Pi 3' in pi_model.stdout"
  notify: Reboot System

- name: Add appropriate dtoverlay configuration to /boot/firmware/config.txt for other models
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    insertafter: EOF
    line: 'dtoverlay=disable-bt'
    create: true
  when: "'Raspberry Pi 3' not in pi_model.stdout"
  notify: Reboot System

- name: Disable and mask unnecessary services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    masked: true
    state: stopped
  loop:
    - serial-getty@ttyAMA0
    - hciuart
    - bluealsa
    - bluetooth
  ignore_errors: true
  notify: Reboot System
