---
- name: Check if DVM service exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/dvm_{{ item }}.service"
  loop: "{{ dvm_services }}"
  register: services_status

- name: Start DVM service if it exists
  ansible.builtin.systemd:
    name: "dvm_{{ item.item }}.service"
    state: started
    enabled: true
  loop: "{{ services_status.results }}"
  when: item.stat.exists
